# Configuration for Travis CI
language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - kcov
after_success: |
  kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/notes_toolbox-* &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
